version: '3.8'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: train_db
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db-data:/var/lib/mysql
      - ./data:/var/lib/mysql-files # This mounts the ./data directory from your host to /var/lib/mysql-files in the container
    command: --local-infile=1 # This enables the use of LOAD DATA INFILE command

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672" # Management console
      - "5672:5672"   # RabbitMQ server
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  db-data:
